default:
  before_script:
    - pip install pdm

test:
  parallel:
    matrix:
     - PYTHON: ["3.9", "3.10", "3.11"]
  image: python:$PYTHON
  script:
    - pdm install -G test
    - pdm run pytest
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
