name: Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install PDM
        run: pip install pdm==2.4.7

      - name: Install test dependencies
        run: pdm install -G test
      
      - name: Run pytest
        run: pdm run pytest
